#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_PKDIENTU_20042025.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_PKDIENTU_20042025")]
	public partial class DB_PKDIENTU_20042025DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSys_user(Sys_user instance);
    partial void UpdateSys_user(Sys_user instance);
    partial void DeleteSys_user(Sys_user instance);
        #endregion
        public DB_PKDIENTU_20042025DataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_PKDIENTU_20042025ConnectionString1"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public DB_PKDIENTU_20042025DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PKDIENTU_20042025DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PKDIENTU_20042025DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_PKDIENTU_20042025DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sys_user> Sys_users
		{
			get
			{
				return this.GetTable<Sys_user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_user")]
	public partial class Sys_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<byte> _ID;
		
		private string _ma_user;
		
		private string _ten_user;
		
		private string _ten_user2;
		
		private string _password;
		
		private System.Nullable<byte> _admin;
		
		private System.Nullable<byte> _acc;
		
		private System.Nullable<byte> _inv;
		
		private string _cmnd;
		
		private string _dia_chi;
		
		private System.Nullable<byte> _status;
		
		private string _ghi_chu;
		
		private System.Nullable<byte> _user0;
		
		private System.Nullable<byte> _user1;
		
		private System.Nullable<System.DateTime> _datetime0;
		
		private System.Nullable<System.DateTime> _datetime1;
		
		private System.Nullable<System.DateTime> _ngay_khoa_1;
		
		private System.Nullable<System.DateTime> _ngay_khoa_2;
		
		private System.Nullable<byte> _quyen_qtsx;
		
		private System.Nullable<byte> _quyen_qtkd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Nullable<byte> value);
    partial void OnIDChanged();
    partial void Onma_userChanging(string value);
    partial void Onma_userChanged();
    partial void Onten_userChanging(string value);
    partial void Onten_userChanged();
    partial void Onten_user2Changing(string value);
    partial void Onten_user2Changed();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnadminChanging(System.Nullable<byte> value);
    partial void OnadminChanged();
    partial void OnaccChanging(System.Nullable<byte> value);
    partial void OnaccChanged();
    partial void OninvChanging(System.Nullable<byte> value);
    partial void OninvChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    partial void Onuser0Changing(System.Nullable<byte> value);
    partial void Onuser0Changed();
    partial void Onuser1Changing(System.Nullable<byte> value);
    partial void Onuser1Changed();
    partial void Ondatetime0Changing(System.Nullable<System.DateTime> value);
    partial void Ondatetime0Changed();
    partial void Ondatetime1Changing(System.Nullable<System.DateTime> value);
    partial void Ondatetime1Changed();
    partial void Onngay_khoa_1Changing(System.Nullable<System.DateTime> value);
    partial void Onngay_khoa_1Changed();
    partial void Onngay_khoa_2Changing(System.Nullable<System.DateTime> value);
    partial void Onngay_khoa_2Changed();
    partial void Onquyen_qtsxChanging(System.Nullable<byte> value);
    partial void Onquyen_qtsxChanged();
    partial void Onquyen_qtkdChanging(System.Nullable<byte> value);
    partial void Onquyen_qtkdChanged();
    #endregion
		
		public Sys_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="TinyInt")]
		public System.Nullable<byte> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_user", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_user
		{
			get
			{
				return this._ma_user;
			}
			set
			{
				if ((this._ma_user != value))
				{
					this.Onma_userChanging(value);
					this.SendPropertyChanging();
					this._ma_user = value;
					this.SendPropertyChanged("ma_user");
					this.Onma_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_user", DbType="NVarChar(100)")]
		public string ten_user
		{
			get
			{
				return this._ten_user;
			}
			set
			{
				if ((this._ten_user != value))
				{
					this.Onten_userChanging(value);
					this.SendPropertyChanging();
					this._ten_user = value;
					this.SendPropertyChanged("ten_user");
					this.Onten_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_user2", DbType="NVarChar(100)")]
		public string ten_user2
		{
			get
			{
				return this._ten_user2;
			}
			set
			{
				if ((this._ten_user2 != value))
				{
					this.Onten_user2Changing(value);
					this.SendPropertyChanging();
					this._ten_user2 = value;
					this.SendPropertyChanged("ten_user2");
					this.Onten_user2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="TinyInt")]
		public System.Nullable<byte> admin
		{
			get
			{
				return this._admin;
			}
			set
			{
				if ((this._admin != value))
				{
					this.OnadminChanging(value);
					this.SendPropertyChanging();
					this._admin = value;
					this.SendPropertyChanged("admin");
					this.OnadminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc", DbType="TinyInt")]
		public System.Nullable<byte> acc
		{
			get
			{
				return this._acc;
			}
			set
			{
				if ((this._acc != value))
				{
					this.OnaccChanging(value);
					this.SendPropertyChanging();
					this._acc = value;
					this.SendPropertyChanged("acc");
					this.OnaccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inv", DbType="TinyInt")]
		public System.Nullable<byte> inv
		{
			get
			{
				return this._inv;
			}
			set
			{
				if ((this._inv != value))
				{
					this.OninvChanging(value);
					this.SendPropertyChanging();
					this._inv = value;
					this.SendPropertyChanged("inv");
					this.OninvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(20)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(200)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="NVarChar(2000)")]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user0", DbType="TinyInt")]
		public System.Nullable<byte> user0
		{
			get
			{
				return this._user0;
			}
			set
			{
				if ((this._user0 != value))
				{
					this.Onuser0Changing(value);
					this.SendPropertyChanging();
					this._user0 = value;
					this.SendPropertyChanged("user0");
					this.Onuser0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user1", DbType="TinyInt")]
		public System.Nullable<byte> user1
		{
			get
			{
				return this._user1;
			}
			set
			{
				if ((this._user1 != value))
				{
					this.Onuser1Changing(value);
					this.SendPropertyChanging();
					this._user1 = value;
					this.SendPropertyChanged("user1");
					this.Onuser1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datetime0", DbType="DateTime")]
		public System.Nullable<System.DateTime> datetime0
		{
			get
			{
				return this._datetime0;
			}
			set
			{
				if ((this._datetime0 != value))
				{
					this.Ondatetime0Changing(value);
					this.SendPropertyChanging();
					this._datetime0 = value;
					this.SendPropertyChanged("datetime0");
					this.Ondatetime0Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datetime1", DbType="DateTime")]
		public System.Nullable<System.DateTime> datetime1
		{
			get
			{
				return this._datetime1;
			}
			set
			{
				if ((this._datetime1 != value))
				{
					this.Ondatetime1Changing(value);
					this.SendPropertyChanging();
					this._datetime1 = value;
					this.SendPropertyChanged("datetime1");
					this.Ondatetime1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_khoa_1", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngay_khoa_1
		{
			get
			{
				return this._ngay_khoa_1;
			}
			set
			{
				if ((this._ngay_khoa_1 != value))
				{
					this.Onngay_khoa_1Changing(value);
					this.SendPropertyChanging();
					this._ngay_khoa_1 = value;
					this.SendPropertyChanged("ngay_khoa_1");
					this.Onngay_khoa_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_khoa_2", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> ngay_khoa_2
		{
			get
			{
				return this._ngay_khoa_2;
			}
			set
			{
				if ((this._ngay_khoa_2 != value))
				{
					this.Onngay_khoa_2Changing(value);
					this.SendPropertyChanging();
					this._ngay_khoa_2 = value;
					this.SendPropertyChanged("ngay_khoa_2");
					this.Onngay_khoa_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen_qtsx", DbType="TinyInt")]
		public System.Nullable<byte> quyen_qtsx
		{
			get
			{
				return this._quyen_qtsx;
			}
			set
			{
				if ((this._quyen_qtsx != value))
				{
					this.Onquyen_qtsxChanging(value);
					this.SendPropertyChanging();
					this._quyen_qtsx = value;
					this.SendPropertyChanged("quyen_qtsx");
					this.Onquyen_qtsxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen_qtkd", DbType="TinyInt")]
		public System.Nullable<byte> quyen_qtkd
		{
			get
			{
				return this._quyen_qtkd;
			}
			set
			{
				if ((this._quyen_qtkd != value))
				{
					this.Onquyen_qtkdChanging(value);
					this.SendPropertyChanging();
					this._quyen_qtkd = value;
					this.SendPropertyChanged("quyen_qtkd");
					this.Onquyen_qtkdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
